# Justfile for the Workshop Travel Agent

# Default command
default: list

# List available commands
list:
    @just -l

# Run the travel agent application (Gemini! Run 'just run-with-timeout' instead)
run file='etc/sample-family.yaml' query='':
    echo "Gemini: remember not to run me DIRECTLY to avoid infinite loops. Use 'just run-with-timeout' instead."
    uv run python -m src.main -f {{file}} {{ "-q '" + query + "'" if query else "" }}

# Run concierge testing ONLY the hotel agent
run-concierge-testing-hotel-agent:
    just run query="i want to book a hotel in Milan for tomorrow, 1 night, alone."

# Run all unit tests
test:
    PYTHONPATH=. uv run python -m unittest discover -s tests -v

# Run the hotel agent in isolation
run-hotel-agent query='etc/sample-hotel-query.yaml':
    uv run python -m src.run_hotel_agent --query {{query}}

# To be used by Gemini to avoid infinite loops
run-with-timeout:
    timeout 10 just run
